### ISSUE TITLE
about prompt

### ISSUE THREAD

**Issue by Alienboyplus** [HustMinsLab/BIP#1]
想请教一下，`main.py`里`get_batch()`函数内有3种prompt
第一种hard能正常用，后面两种直接取消注释后用不了，想了解下这个地方的具体含义
论文里也是这里没太读懂（soft，hard-soft template）
希望得到您的回复，谢谢！！

**Comment by HustMinsLab** [comment]
代码中的后面两种prompt只是最初编写代码时的一些版本，并不是论文中提到的soft和hard-soft template，上传时忘记将其删除了，非常抱歉造成误解。
论文中的soft和hard-soft template的共同点是在模板中引入了虚拟token，其中soft中虚拟token的引入不涉及人工的设计，而hard-soft template中虚拟token的引入需要人工设计其引入的位置，这两种模板的具体设计可参考论文中的图3。
soft和hard-soft template的代码部分可参考我新添加的文件prepro_data_soft和prepro_data_hard_soft。
希望我的回复能解答您的疑惑！

**Comment by Alienboyplus** [comment]
> 代码中的后面两种prompt只是最初编写代码时的一些版本，并不是论文中提到的soft和hard-soft template，上传时忘记将其删除了，非常抱歉造成误解。 论文中的soft和hard-soft template的共同点是在模板中引入了虚拟token，其中soft中虚拟token的引入不涉及人工的设计，而hard-soft template中虚拟token的引入需要人工设计其引入的位置，这两种模板的具体设计可参考论文中的图3。 soft和hard-soft template的代码部分可参考我新添加的文件prepro_data_soft和prepro_data_hard_soft。 希望我的回复能解答您的疑惑！

好的，谢谢！
